watch:
	open http://localhost:8080/README.md
	../../.engine/node_modules/@marp-team/marp-cli/marp-cli.js --engine ../../.engine/engine.js --allow-local-files --server .

build:
	../../.engine/node_modules/@marp-team/marp-cli/marp-cli.js --engine ../../.engine/engine.js --html --allow-local-files README.md -o slides.pptx

pdf:
	../../.engine/node_modules/@marp-team/marp-cli/marp-cli.js --engine ../../.engine/engine.js --html --allow-local-files README.md -o slides.pdf
