build:
	../.engine/node_modules/@marp-team/marp-cli/marp-cli.js --engine ../.engine/engine.js  --allow-local-files slides.md -o slides.pptx

watch:
	../.engine/node_modules/@marp-team/marp-cli/marp-cli.js --engine ../.engine/engine.js --server .

pdf:
	../.engine/node_modules/@marp-team/marp-cli/marp-cli.js --engine ../.engine/engine.js  --allow-local-files slides.md -o slides.pdf
