require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2

Style/QuotedSymbols:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false
