build:
	../.engine/node_modules/@marp-team/marp-cli/marp-cli.js --engine ../.engine/engine.js  --allow-local-files README.md -o slides.pptx

watch:
	../.engine/node_modules/@marp-team/marp-cli/marp-cli.js --engine ../.engine/engine.js -w README.md -o slides.html

pdf:
	../.engine/node_modules/@marp-team/marp-cli/marp-cli.js --engine ../.engine/engine.js  --allow-local-files README.md -o slides.pdf
